# Generated by Django 4.2.20 on 2025-04-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises_app", "0004_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
