# Generated by Django 4.2.20 on 2025-04-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises_app", "0005_alter_category_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.AddField(
            model_name="category",
            name="my_id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
