# Generated by Django 5.2 on 2025-04-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises_app", "0006_remove_category_id_category_my_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("author", models.CharField(max_length=64, null=True)),
                ("content", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "in writing"),
                            (2, "pending editor approval"),
                            (3, "published"),
                        ]
                    ),
                ),
                ("publish_date", models.DateField(null=True)),
                ("removal_date", models.DateField(null=True)),
            ],
        ),
    ]
