# Generated by Django 5.2 on 2025-04-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises_app", "0007_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_title", models.CharField(max_length=64)),
                ("release_year", models.IntegerField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (0, "very bad"),
                            (1, "poor"),
                            (2, "average"),
                            (3, "good"),
                            (4, "very good"),
                            (5, "excellent"),
                        ]
                    ),
                ),
            ],
        ),
    ]
