# Generated by Django 5.2 on 2025-04-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises_app", "0008_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="band",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="exercises_app.band",
            ),
        ),
    ]
