# Generated by Django 5.2 on 2025-04-27 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises_app", "0009_album_band"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("duration", models.TimeField(null=True)),
                (
                    "album",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises_app.album",
                    ),
                ),
            ],
        ),
    ]
