# Generated by Django 5.2 on 2025-04-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises_app", "0010_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="articles",
            field=models.ManyToManyField(to="exercises_app.article"),
        ),
    ]
