# Generated by Django 5.2 on 2025-04-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises_app", "0011_category_articles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_name", models.CharField(max_length=64)),
                ("salary", models.FloatField()),
                (
                    "person",
                    models.OneToOneField(
                        default=-1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exercises_app.person",
                    ),
                ),
            ],
        ),
    ]
